---
title: "Anil Menon"
author: "Anil Menon"
date: "2020-01-31"
output: html_document
---

***Warring Memories: The Political Behavior Legacies of World War II in Germany***

Does conflict-induced resettlement produce durable political behavior legacies? I investigate this question by focusing on the expulsion of ethnic Germans from Eastern Europe into West Germany at the end of World War II. These expellees wanted to regain their lost lands and for broader society to acknowledge their suffering. In time, such demands for recognition and restitution received little support outside far-right parties. Leveraging district-level data from 32 elections spanning 100 years, I find that communities which received a greater share of expellees remain more likely to support the far right in the short, medium, and long term. This durable and robust relationship, nevertheless, appears sensitive to temporal changes in how World War II is remembered within Germany. Moreover, analyses of expellee subgroups suggest that behavioral legacies from conflict-induced resettlement can be heterogeneous. Specifically, the observed relationship between expellee share and far-right support is driven primarily by districts that received greater shares of those expellees who were the most politically organized.

<a href="https://drive.google.com/open?id=1VMpkBGx5UpSTDNrjdd_LbwH1wHtGsE68">Download the paper here (U-M only)</a>\