---
title: "Hojung Joo"
author: "Hojung Joo"
date: "2020-01-24"
output: html_document
---

***Colonial grievances and uprisings in Korea***

Does history matter when it comes to explaining violence against civilians during wars? How does a region’s history of communal conflict or resistance against authority influence the intentional killing of civilians by armed groups? In this paper, I argue that a region that have more records of economic tension among villagers also experience more violence against civilians during future armed conflicts. I further argue that a region’s record of resistance against authority, conditional on the relationship between past and current authorities, can lead to more civilian killings. I utilize new data about colonial protests against Japanese rule (1919) and local landlords (1930s) at the county level to explain variation in civilian killings during the Korean War (1950-1953). I find that a region that has a history of conflict between peasants and landlords during the colonial period experience a significantly higher number of civilian killings, regardless of the type of perpetrator. I also find that having a history of resistance against Japanese colonial authority leads to higher killings perpetrated by the South Korean armed forces, but lower killings by the North Korean armed forces. The findings also show that regions that experience violence in earlier periods of the war generally also face relatively higher levels of violence in later periods during the war, hinting the dynamics of “violence begets violence.”

<a href="https://drive.google.com/open?id=1bR9Ja7RIxu0IQtFuIh0N2ZD5wyNRFy4u">Download the paper here (U-M only)</a>\











