---
title: "Sasha de Vogel"
author: "Sasha de Vogel"
date: "2020-01-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

***Information, Concessions and Reneging in Authoritarian Regimes***

How does information affect how autocratic governments make concessions to subnational protest campaigns? I argue the strategic purpose of concessions varies depending on the level of information about the grievance available to the government. In cases where the government has little prior awareness of the motivating grievance, protests convey valuable new information, and concessions are used as a long-term adaptation strategy, to eliminate grievances and prevent citizens from becoming regime opponents. In many cases, however, the government already possesses information that policies it desires to pursue are unpopular and will produce protest. Here, the government has sufficient information that it deliberately avoids or manipulates consultative institutions. Concessions are then used as a short-term demobilization strategy to disrupt a campaign’s capacity to mobilize. Once mobilization diminishes, the government can renege, or deliberately fail to implement the promised concession and pursues its desired policies unchanged. I test the implications of this theory with an original dataset, Protest Campaigns of Moscow (PCoM), which contains observations on 64 protest campaigns held in Moscow, Russia, against the city government, from 2013-2018. Based on extensive data collection from Russian-language social networking sites, mass media, and interest-group specific websites, this is the first campaign-level dataset to include detailed information about the implementation of concessions up to four years after the initial government promise. I find that when the government deliberately avoided acquiring public opinion information, reneging occurred in 61% of cases, whereas when consultation was not avoided, reneging occurred in 38% of cases. 

<a href="https://drive.google.com/open?id=1_WerVGBIb8X3Zy3hKQQGQ8ucajRAm6Y-">Download the paper here (U-M only)</a>\