---
title: "November 8 Presentation: Sarah Khan (Yale University)"
author: "Sarah Khan"
date: "2019-11-08"
output: html_document
---
**Canvassing the Gatekeepers: A Field Experiment to Increase Women's Electoral Turnout in Pakistan**\
Ali Cheema, Sarah Khan, Asad Liaqat, and Shandana Khan Mohmand\

*Abstract*\
Pakistan has one of the largest gender gaps in turnout among electoral democracies around the world. A widely tested strategy to encourage turnout in a variety of contexts is door-to-door voter canvassing or mobilization. We use a field experiment conducted with 2500 households in the city of Lahore to study the effectiveness of this strategy in increasing women's turnout in the 2018 Pakistan General Election. We find that non-partisan mobilization only improves women's turnout when mobilizers target men in households, and that targeting women alone is insufficient to effect changes in women's political participation on Election Day. Using a costly behavioral measure of support for women's role in democracy, we find that targeting men with the canvassing treatment increases their expressed support for women's role in democracy beyond Election Day. Results from a post-election survey suggest that households where both men and women received the treatment saw greater political discussion among men and women, and that men provided women in these households with logistical support to vote on Election Day. These findings have theoretical implications for understanding women's political participation in a context where they enjoy limited agency within the household, and practical implications for designing effective interventions to improve their participation under such conditions.