---
title: "September 12: WCED Colloquium on Authoritarian Politics: Iza Ding and Jeffrey Javed"
author: "Iza Ding and Jeffrey Javed"
date: "2019-09-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
**Red Memory: Nostalgia, Trauma, and Public Opinion in Contemporary China**\
Iza Ding (University of Pittsburg) and Jeffrey Javed (University of Michigan)\

*Abstract*\
How do citizens remember the political past and how do these memories shape their views of present-day politics? We examine the formation of political memory and its relationship with individual attitudes toward contemporary government policies in China, focusing on Chinese citizens’ memories of the Maoist era (1949-1976). On the basis of 77 intensive semi-structured interviews in four cities, we find that Maoist nostalgia—where it exists—is a reaction to the profound feeling of moral disenchantment many Chinese citizens feel over the complex societal challenges resulting from China’s extraordinary four-decade arc of economic reform. However, Maoist nostalgia is best described as is "reflective" rather than "restorative": people may believe that Chinese society has lost a sense of purpose under market capitalism, they do not miss the material hardship of the Maoist era, which they also vividly remember. In addition, we find that individual’s memories and assessments of the Maoist era are correlated with their attitudes towards contemporary public policies, such as Xi’s anti-corruption campaign. One particular subset of respondents, whom we call “nostalgic hardliners,” exhibit strong reflective nostalgia toward the Maoist era; they are more supportive of the current anti-corruption campaign and even more punitive measures to curb corruption. This research informs a broader discussion of how political memory influences how people evaluate contemporary politics.

*This presentation is organized by the WCED Colloquium on Authoritarian Politics. It will take place on **September 12 at 5pm in 555 Weiser Hall**. The talk will be followed by a reception.*