---
title: "Michael Lerner"
author: "Michael Lerner"
date: "2020-02-14"
output: html_document
---

***Do interaction and advocacy catalyze environmental policy leadership?***

International efforts to address environmental challenges increasingly rely on the information, capacity, and will of policymakers to act as policy leaders at the national level. What countries have taken the lead in the development of environmental policy? Do international interaction and transnational advocacy catalyze environmental policy leadership? Combining a novel network-based measurement approach and a new database of environmental policy innovation adoptions, I will dynamically measure environmental policy leadership at the global level and estimate its relationship with interaction and advocacy using causally-identified spatial and network regression models. I supplement this statistical analysis with a comparative case study to investigate the mechanisms by which international interaction and transnational advocacy increase the inventiveness and influence of environmental policymakers. Through my dissertation, I hope to contribute to the study of policy leadership, policy diffusion, and transnational environmental advocacy, as well as the practical challenge of fostering leadership in environmental policy.

<a href="https://drive.google.com/open?id=11PL8fZXCfBe5kFrlG9qOlrL9omH11vGJ">Download the paper here (U-M only)</a>\