---
title: "Htet Thiha Zaw"
author: "Htet Thiha Zaw"
date: "2020-10-02"
output: html_document
---

***Repression and (Re)Education: A Theory of Institutional Change in Colonial Education***

Why did colonial states expand their involvement in educating their indigenous populations? Observed across colonial Southeast Asia, this phenomenon's characteristic feature is not explained by existing research: a policy change from the early support for indigenous providers to their later replacement by secular and missionary schools. To illustrate this, I conceptualize colonial education as a commitment problem, where the government, despite economic benefits from education, faces the risk of anti-colonial resistance from the educated population. I propose that, under low anti-colonial resistance, the government relies on indigenous providers to reap economic benefits, and under high anti-colonial resistance is low, it replaces them for more control over ideological content. I expect a gradual shift in education's dominant purpose, from training bureaucrats to building a national identity. The theory merges existing research on education's role as an economic good and an ideological good, showing the dynamics of its role in shaping colonial education.












